DROP TABLE IF EXISTS DOCUMENTS;
CREATE TABLE DOCUMENTS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    doc_name VARCHAR(50) NOT NULL,
    document_path VARCHAR(50) NULL,
    post_date VARCHAR(50) NOT NULL,
    posts VARCHAR(50) NULL,
    comments VARCHAR(50) NULL
);